export function list() {
  return [
    { unit: "USD", name: " United States Dollar" },
    { unit: "AED", name: "United Arab Emirates Dirham" },
    { unit: "AFN", name: "Afghan Afghani" },
    { unit: "ALL", name: "Albanian Lek" },
    { unit: "AMD", name: "Armenian Dram" },
    { unit: "ANG", name: "Netherlands Antillean Guilder" },
    { unit: "AOA", name: "Angolan Kwanza" },
    { unit: "ARS", name: "Argentine Peso" },
    { unit: "AUD", name: "Australian Dollar" },
    { unit: "AWG", name: "Aruban Florin" },
    { unit: "AZN", name: "Azerbaijani Manat" },
    { unit: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
    { unit: "BBD", name: "Barbadian Dollar" },
    { unit: "BDT", name: "Bangladeshi Taka" },
    { unit: "BGN", name: "Bulgarian Lev" },
    { unit: "BHD", name: "Bahraini Dinar" },
    { unit: "BIF", name: "Burundian Franc" },
    { unit: "BMD", name: "Bermudan Dollar" },
    { unit: "BND", name: "Brunei Dollar" },
    { unit: "BOB", name: "Bolivian Boliviano" },
    { unit: "BRL", name: "Brazilian Real" },
    { unit: "BSD", name: "Bahamian Dollar" },
    { unit: "BTN", name: "Bhutanese Ngultrum" },
    { unit: "BWP", name: "Botswanan Pula" },
    { unit: "BYN", name: "New Belarusian Ruble" },
    { unit: "BZD", name: "Belize Dollar" },
    { unit: "CAD", name: "Canadian Dollar" },
    { unit: "CDF", name: "Congolese Franc" },
    { unit: "CHF", name: "Swiss Franc" },
    { unit: "CLP", name: "Chilean Peso" },
    { unit: "CNY", name: "Chinese Yuan" },
    { unit: "COP", name: "Colombian Peso" },
    { unit: "CRC", name: "Costa Rican Colón" },
    { unit: "CUC", name: "Cuban Convertible Peso" },
    { unit: "CUP", name: "Cuban Peso" },
    { unit: "CVE", name: "Cape Verdean Escudo" },
    { unit: "CZK", name: "Czech Republic Koruna" },
    { unit: "DJF", name: "Djiboutian Franc" },
    { unit: "DKK", name: "Danish Krone" },
    { unit: "DOP", name: "Dominican Peso" },
    { unit: "DZD", name: "Algerian Dinar" },
    { unit: "EGP", name: "Egyptian Pound" },
    { unit: "ERN", name: "Eritrean Nakfa" },
    { unit: "ETB", name: "Ethiopian Birr" },
    { unit: "EUR", name: "Euro" },
    { unit: "FJD", name: "Fijian Dollar" },
    { unit: "FKP", name: "Falkland Islands Pound" },
    { unit: "GBP", name: "British Pound Sterling" },
    { unit: "GEL", name: "Georgian Lari" },
    { unit: "GGP", name: "Guernsey Pound" },
    { unit: "GHS", name: "Ghanaian Cedi" },
    { unit: "GIP", name: "Gibraltar Pound" },
    { unit: "GMD", name: "Gambian Dalasi" },
    { unit: "GNF", name: "Guinean Franc" },
    { unit: "GTQ", name: "Guatemalan Quetzal" },
    { unit: "GYD", name: "Guyanaese Dollar" },
    { unit: "HKD", name: "Hong Kong Dollar" },
    { unit: "HNL", name: "Honduran Lempira" },
    { unit: "HRK", name: "Croatian Kuna" },
    { unit: "HTG", name: "Haitian Gourde" },
    { unit: "HUF", name: "Hungarian Forint" },
    { unit: "IDR", name: "Indonesian Rupiah" },
    { unit: "ILS", name: "Israeli New Sheqel" },
    { unit: "IMP", name: "Manx pound" },
    { unit: "INR", name: "Indian Rupee" },
    { unit: "IQD", name: "Iraqi Dinar" },
    { unit: "IRR", name: "Iranian Rial" },
    { unit: "ISK", name: "Icelandic Króna" },
    { unit: "JEP", name: "Jersey Pound" },
    { unit: "JMD", name: "Jamaican Dollar" },
    { unit: "JOD", name: "Jordanian Dinar" },
    { unit: "JPY", name: "Japanese Yen" },
    { unit: "KES", name: "Kenyan Shilling" },
    { unit: "KGS", name: "Kyrgystani Som" },
    { unit: "KHR", name: "Cambodian Riel" },
    { unit: "KMF", name: "Comorian Franc" },
    { unit: "KPW", name: "North Korean Won" },
    { unit: "KRW", name: "South Korean Won" },
    { unit: "KWD", name: "Kuwaiti Dinar" },
    { unit: "KYD", name: "Cayman Islands Dollar" },
    { unit: "KZT", name: "Kazakhstani Tenge" },
    { unit: "LAK", name: "Laotian Kip" },
    { unit: "LBP", name: "Lebanese Pound" },
    { unit: "LKR", name: "Sri Lankan Rupee" },
    { unit: "LRD", name: "Liberian Dollar" },
    { unit: "LSL", name: "Lesotho Loti" },
    { unit: "LYD", name: "Libyan Dinar" },
    { unit: "MAD", name: "Moroccan Dirham" },
    { unit: "MDL", name: "Moldovan Leu" },
    { unit: "MGA", name: "Malagasy Ariary" },
    { unit: "MKD", name: "Macedonian Denar" },
    { unit: "MMK", name: "Myanma Kyat" },
    { unit: "MNT", name: "Mongolian Tugrik" },
    { unit: "MOP", name: "Macanese Pataca" },
    { unit: "MRO", name: "Mauritanian Ouguiya" },
    { unit: "MUR", name: "Mauritian Rupee" },
    { unit: "MVR", name: "Maldivian Rufiyaa" },
    { unit: "MWK", name: "Malawian Kwacha" },
    { unit: "MXN", name: "Mexican Peso" },
    { unit: "MYR", name: "Malaysian Ringgit" },
    { unit: "MZN", name: "Mozambican Metical" },
    { unit: "NAD", name: "Namibian Dollar" },
    { unit: "NGN", name: "Nigerian Naira" },
    { unit: "NIO", name: "Nicaraguan Córdoba" },
    { unit: "NOK", name: "Norwegian Krone" },
    { unit: "NPR", name: "Nepalese Rupee" },
    { unit: "NZD", name: "New Zealand Dollar" },
    { unit: "OMR", name: "Omani Rial" },
    { unit: "PAB", name: "Panamanian Balboa" },
    { unit: "PEN", name: "Peruvian Nuevo Sol" },
    { unit: "PGK", name: "Papua New Guinean Kina" },
    { unit: "PHP", name: "Philippine Peso" },
    { unit: "PKR", name: "Pakistani Rupee" },
    { unit: "PLN", name: "Polish Zloty" },
    { unit: "PYG", name: "Paraguayan Guarani" },
    { unit: "QAR", name: "Qatari Rial" },
    { unit: "RON", name: "Romanian Leu" },
    { unit: "RSD", name: "Serbian Dinar" },
    { unit: "RUB", name: "Russian Ruble" },
    { unit: "RWF", name: "Rwandan Franc" },
    { unit: "SAR", name: "Saudi Riyal" },
    { unit: "SBD", name: "Solomon Islands Dollar" },
    { unit: "SCR", name: "Seychellois Rupee" },
    { unit: "SDG", name: "Sudanese Pound" },
    { unit: "SEK", name: "Swedish Krona" },
    { unit: "SGD", name: "Singapore Dollar" },
    { unit: "SHP", name: "Saint Helena Pound" },
    { unit: "SLL", name: "Sierra Leonean Leone" },
    { unit: "SOS", name: "Somali Shilling" },
    { unit: "SRD", name: "Surinamese Dollar" },
    { unit: "STD", name: "São Tomé and Príncipe Dobra" },
    { unit: "SVC", name: "Salvadoran Colón" },
    { unit: "SYP", name: "Syrian Pound" },
    { unit: "SZL", name: "Swazi Lilangeni" },
    { unit: "THB", name: "Thai Baht" },
    { unit: "TJS", name: "Tajikistani Somoni" },
    { unit: "TMT", name: "Turkmenistani Manat" },
    { unit: "TND", name: "Tunisian Dinar" },
    { unit: "TOP", name: "Tongan Paʻanga" },
    { unit: "TRY", name: "Turkish Lira" },
    { unit: "TTD", name: "Trinidad and Tobago Dollar" },
    { unit: "TWD", name: "New Taiwan Dollar" },
    { unit: "TZS", name: "Tanzanian Shilling" },
    { unit: "UAH", name: "Ukrainian Hryvnia" },
    { unit: "UGX", name: "Ugandan Shilling" },
    { unit: "USD", name: "United States Dollar" },
    { unit: "UYU", name: "Uruguayan Peso" },
    { unit: "UZS", name: "Uzbekistan Som" },
    { unit: "VEF", name: "Venezuelan Bolívar Fuerte" },
    { unit: "VND", name: "Vietnamese Dong" },
    { unit: "VUV", name: "Vanuatu Vatu" },
    { unit: "WST", name: "Samoan Tala" },
    { unit: "XAF", name: "CFA Franc BEAC" },
    { unit: "XCD", name: "East Caribbean Dollar" },
    { unit: "XOF", name: "CFA Franc BCEAO" },
    { unit: "XPF", name: "CFP Franc" },
    { unit: "YER", name: "Yemeni Rial" },
    { unit: "ZAR", name: "South African Rand" },
    { unit: "ZMW", name: "Zambian Kwacha" },
  ];
}
